language: cpp
sudo: false
before_install:
   - eval "${MATRIX_EVAL}"
matrix:
  fast_finish: true
  include:
  - os: osx
    compiler: clang
    script:
    - conan install --build=missing
    - cmake . -DNO_GPU=ON
    - make -j$(nproc)
    env:
    - NAME="osx clang" MATRIX_EVAL="brew install conan"
    cache:
      directories:
      - $HOME/.conan
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - rpm-build
    env:
    - NAME="linux g++-5" MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    script:
    - pip install conan --user
    - conan install --build=missing
    - cmake . -DNO_GPU=ON
    - make -j$(nproc)
    - make package
    cache:
      directories:
      - $HOME/.conan
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - NAME="linux g++-6" MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    script:
    - pip install conan --user
    - conan install --build=missing
    - cmake . -DNO_GPU=ON
    - make -j$(nproc)
    cache:
      directories:
      - $HOME/.conan
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - NAME="linux g++-7" - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    script:
    - pip install conan --user
    - conan install --build=missing
    - cmake . -DNO_GPU=ON
    - make -j$(nproc)
    cache:
      directories:
      - $HOME/.conan

