language: cpp
dist: trusty
compiler: gcc
group: stable
matrix:
  fast_finish: true
  include:
    - os: osx
      compiler: clang
      script:
        - sh install.sh
    - os: linux
      compiler: gcc
      addons:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
        env:
          - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      script:
        - sh install.sh
before_install:
   - eval "${MATRIX_EVAL}"
